### ISSUE TITLE
Posted dates are not consistent with local (French) format

### ISSUE THREAD

**Issue by Limezy** [buckets/translations#17]
Should be "25 Avr. 2018" for example.
<img width="485" alt="image" src="https://user-images.githubusercontent.com/24638389/39315007-3ae5978a-49a8-11e8-98ae-b282824f1317.png">

**Comment by iffy** [comment]
This is fixed by the above referenced issue (so I'm closing this one, but the other one will remain open until it's released in the next version of Buckets)
