### ISSUE TITLE
Shall I translate "Buckets" ?

### ISSUE THREAD

**Issue by Limezy** [buckets/translations#8]
Hi, 

Just started to translate your software into French (2/3 done already).
I have a general question : shall I translate the word "Buckets" ?
On one hand, it's the name of the software, "Budget with Buckets" is your "marketing" name.
On the other hand, "bucket" doesn't mean anything in French and I'm sure that some French people not knowing the English word "bucket" will have troubles understanding why you are taking about "rain", "rainfall"... Not translating "bucket" makes your "budget with buckets" method less natural.

Any thoughts ?

**Comment by iffy** [comment]
I need to mark the translations strings a little better, but in general:

- If "Bucket" is referring to the name of the program, for now, keep it as "Bucket"
- If "bucket" is referring to the categories within the program, translate them to the French word for "bucket"

I should do more research on how other applications translate their names.  I've filed that here: https://trello.com/c/aUkRFrJs/163-should-you-translate-buckets-into-other-languages

**Comment by Limezy** [comment]
OK will do that.
I'm two thirds done but I don't know why I did not manage to make a pull request yet.
I get an SSL error saying I do not have the rights do do so...

**Comment by iffy** [comment]
@Limezy wow!  Merci! Also, please reach out if you come across any other translation questions or if you don't have enough information/context.

As for the SSL error... I'm not sure what that's about.  Are you getting an error while trying to push to GitHub?  Or while trying to create the pull request.
